[package]
name = "macro_handler"
version = "0.1.0"
edition = "2024"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0"
syn = { version = "2.0", features = ["full", "extra-traits"] }
ensure = { version = "0.3", optional = true}
serde-reflection = { version = "0.5.1", optional = true}
quote = "1.0"
darling = "0.20"

[dev-dependencies]
trybuild = "1.0"

[features]
export_ts_type = ["dep:ensure", "dep:serde-reflection"]